import { Card } from "./card";

export const CARD: Card[] = [
    {
       "cardId":0,
       "cardName":"0",
       "isSelected":false
    },
    {
       "cardId":1,
       "cardName":"½",
       "isSelected":false
    },
    {
       "cardId":3,
       "cardName":"1",
       "isSelected":false
    },
    {
       "cardId":4,
       "cardName":"2",
       "isSelected":false
    },
    {
       "cardId":5,
       "cardName":"3",
       "isSelected":false
    },
    {
       "cardId":6,
       "cardName":"5",
       "isSelected":false
    },
    {
       "cardId":7,
       "cardName":"8",
       "isSelected":false
    },
    {
       "cardId":8,
       "cardName":"13",
       "isSelected":false
    },
    {
       "cardId":9,
       "cardName":"20",
       "isSelected":false
    },
    {
       "cardId":10,
       "cardName":"40",
       "isSelected":false
    },
    {
       "cardId":11,
       "cardName":"100",
       "isSelected":false
    }
 ]